### PR TITLE
fix issue 193

### LINKED ISSUE #193: Hazel closes when OpenGl < 4.5
#### Describe the bug
As of now, we check the OpenGL version and create an error when we do not meet the requirements:
https://github.com/TheCherno/Hazel/blob/0716731c8e274f2e3d83aefef2222fe189a33728/Hazel/src/Platform/OpenGL/OpenGLContext.cpp#L30-L35

However, depending on the VS install, the default settings might close the debugger when the program exits (after the error), so the user has no way of noticing the error (let alone read it)

#### To Reproduce
Start Hazel with an OpenGL version < 4.5 and you won't be able to read the error

#### Expected behavior
Have a way of notifying the user that they do not meet the minimal requirements, in this case we (discord conversation) where thinking of implementing the log file(s) so we can see the errors, even if Hazel closes unexpectedly (or unintended).

### PR DESCRIPTION
**Pull request by HerrDingenz**
#### Describe the issue (if no issue has been made)
As stated in Issue #193 there is a need for the implementation of file loggers.

#### PR impact _(Make sure to add [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords))_
List of related issues/PRs this will solve:

 Impact                  | Issue/PR
------------------------ | ------
Issues this solves       | Closes #193
Other PRs this solves    | None or #number(s)

#### Proposed fix _(Make sure you've read [on how to contribute](https://github.com/TheCherno/Hazel/blob/master/.github/CONTRIBUTING.md) to Hazel)_
I implemented a file logger for both Hazel Core and Hazel Client.
The Hazel Core file logger will create a file named "hazel-log.txt".
The Client file logger will create a file named "client-log.txt".

The console loggers will only be available in Debug builds while the file loggers will be available in Debug and Release builds.

NOTE:
I changed an if-statement in Instrumentor.h --- It now checks if the file logger is initialized.

#### Additional context
I tested and ran both Debug and Release build at it seems to work like a charm

### CODE REVIEW

**Comment by HerrDingenz** [comment]
Thanks for your review.

The idea using sinks is pretty nice but:

I didn't use sinks because i wanted to use different patterns for both loggers. I think all that timestamp information just inflates the file logs - and we really don't need that information in there.

For now the macros do the trick - even though we have 4 different loggers now (at least in debug builds). In release builds there are only 2 loggers (the file loggers obviously)

Regarding the filenames you are right - they should fit the other style of hazel filenames.

**Comment by HerrDingenz** [comment]
Ok .. I changed it to use sinks.

But i am not really happy with the result, because now we have the timestamps AND the logger name inside the log files.

Not only increases this the file size - it is useless information!
We shouldn't care about what time the log message occured - cause the files get created per session anyway.
And since we have 2 different files (one for core and one for client) the logger name inside the files is useless in there, too.

For output to the console this information was useful (i mean the name of the logger) and we need that preset there because of color formatting. But for the file loggers it is just data garbage nobody needs inside those files.

And as i stated in my last comment already: we can't use different presets for the loggers anymore when switching to multiple sinks for one logger.

File: Hazel/src/Hazel/Core/Log.cpp [hunk 1]
```diff
@@ -1,21 +1,36 @@
 #include "hzpch.h"
-#include "Hazel/Core/Log.h"
+//#include "Hazel/Core/Log.h"		included in hzpch.h already
```
Comment (CleverSource) [inline Hazel/src/Hazel/Core/Log.cpp]: This should just be removed, someone can easily find out that it's included in the pch without this here.

File: Hazel/src/Hazel/Core/Log.cpp [hunk 2]
```diff
@@ -1,21 +1,36 @@
...
 	Ref<spdlog::logger> Log::s_CoreLogger;
 	Ref<spdlog::logger> Log::s_ClientLogger;
+	Ref<spdlog::sinks::stdout_color_sink_mt> Log::s_ConsoleSink;
 
 	void Log::Init()
 	{
+		s_ConsoleSink = std::make_shared<spdlog::sinks::stdout_color_sink_mt>();
+
+		std::vector<spdlog::sink_ptr> coreSinks;
+		coreSinks.emplace_back(s_ConsoleSink); // VS debug console
```
Comment (CleverSource) [inline Hazel/src/Hazel/Core/Log.cpp]: This isn't necessarily required, but it won't always be the Visual Studio debug console, which somewhat makes this comment useless.

File: Hazel/src/Hazel/Core/Log.cpp (hunk 1 above)
Comment (LovelySanta) [reply Hazel/src/Hazel/Core/Log.cpp]: Cherno mensioned this in one of his videos, we should not rely in Hazel files being included in the precompiled header. The reason we added it to the pch in the first place was because we won't update it often. And especialy in this case where the cpp file should (always) include its header file, so can you please put it back?

Comment (HerrDingenz) [reply Hazel/src/Hazel/Core/Log.cpp]: that is done already .. the include parts of the cpp file are as they have been before my pull request

**Comment by HerrDingenz** [comment]
Thanks for your review again, LovelySanta...

I made some changes to the code.

Now we are using just one sink and only one log file (for both - client and engine log messages).
The log file will simply just be named "Hazel.log" (for now).

I changed the names of the loggers to "ENGINE" and "CLIENT" and added "%L" to the log patterns. I did that to to make it look more straight inside the log file...

ENGINE I: This is an info.
CLIENT C: This is critical!

is more readable than:

HAZEL: This is an info.
APP: This is critical!

or:

HAZEL info: This is an info.
APP critical: This is critical!

The output to the console stays the same as before.

File: Hazel/src/Hazel/Core/Log.cpp (hunk 1 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Core/Log.cpp]: i already put that back yesterday ;)

**Comment by HerrDingenz** [comment]
trying to optimize it as much as i can .. this is my last commit to this PR.

if you're not happy with it then just close it

**Comment by CleverSource** [comment]
I think it should be formatted ``[Severity] Level: Text`` so it could be ``[Critical] Hazel: Some critical text here.``

**Comment by HerrDingenz** [comment]
Done.

**Comment by HerrDingenz** [comment]
I added "*.log" to the ".gitignore" file to make sure the log file doesn't get pushed to the repository.

File: Hazel/src/Hazel/Core/Log.cpp [hunk 3]
```diff
@@ -10,12 +11,22 @@ namespace Hazel {
...
+
+		s_CoreLogger = std::make_shared<spdlog::logger>("HAZEL", begin(logSinks), end(logSinks));
+		spdlog::register_logger(s_CoreLogger);
 		s_CoreLogger->set_level(spdlog::level::trace);
 
-		s_ClientLogger = spdlog::stdout_color_mt("APP");
+		s_ClientLogger = std::make_shared<spdlog::logger>("APP", begin(logSinks), end(logSinks));
+		spdlog::register_logger(s_ClientLogger);
 		s_ClientLogger->set_level(spdlog::level::trace);
+
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Core/Log.cpp]: Remove this last empty line on the function

File: .gitignore [hunk 4]
```diff
@@ -2,6 +2,7 @@
 **/bin/
 !vendor/bin/premake/
 bin-int/
+*.log
```
Comment (LovelySanta) [inline .gitignore]: Maybe make a new group (aka a comment line above) for hazel files?
```.gitignore
# Hazel files
*.log
```

File: Hazel/src/Hazel/Core/Log.cpp (hunk 3 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Core/Log.cpp]: sure

File: .gitignore (hunk 4 above)
Comment (HerrDingenz) [reply .gitignore]: done

**Comment by HerrDingenz** [comment]
well then i guess we are ready to merge :wink:

**Comment by TheCherno** [comment]
Thank you to everyone for their contributions to this, I'd love to merge this in, however, I have a few issues:
- Logged file doesn't seem to contain any timestamps, like the output log does. This would be useful to have
- Flushing the file seems to be tied to the engine shutting down cleanly, which isn't always the case - I would love to have a log file of what happened if the engine crashed, but currently I would just have a blank Hazel.log file

Could we get these issues resolved? I'm open to discussion.

**Comment by HerrDingenz** [comment]
Adding the timestamps back in can be done by just adding them back to the pattern of the file sink. We stripped them out because the log file gets created per session anyway so the timestamps might not be really that necessary in the log file.

For the log file not being filled if the engine crashes that is really an issue. In my first version i did the flushing myself inside the macros everytime a message got put to the file.

**Comment by HerrDingenz** [comment]
Timestamps are added back to the log file.
Flush level for the loggers is set to "trace" - so now spdlog will flush the contents at every message and we will have data inside the log file even if Hazel crashes.
