### PR TITLE
fixed the '__cdecl' output in Instrumentor.h in a 'constexpr' way

### LINKED ISSUE #191: Instrumentator better function name
#### Describe the bug
A followup on https://github.com/TheCherno/Hazel/pull/185#issuecomment-573086649: There is quite a significant overhead by the cleanup of the function name of the instrumentor as mensioned in https://github.com/TheCherno/Hazel/pull/185#issuecomment-569551143.
https://github.com/TheCherno/Hazel/blob/0716731c8e274f2e3d83aefef2222fe189a33728/Hazel/src/Hazel/Debug/Instrumentor.h#L75-L76

As this is already (partialy) resolved, there is still some cleanup to do, as with the different formats of the pretty printing, the std:replace is in some cases unneeded, and in other cases not enough, for example using the msvc compiler, we could still remove the unneeded __cdecl in every function name.

#### To Reproduce
Load a result in [chrome tracing](chrome://tracing/) and check out the function names.

#### Expected behavior
The expected behavior is to have a more uniform function name across (all) compilers.
A possible solution could be to create a static function that returns the correct function name? This function we could differ for each (supported) compiler as we already have the different pretty functions in a macro. This function could even be exposed to other parts of the (future) debugging section of the engine?

### PR DESCRIPTION
**Pull request by HerrDingenz**
#### Describe the issue (if no issue has been made)
It is not really an issue - just a "cosmetic fix". Inside our Instrumentor output we have this annyoing "__cdecl" output on MSVC compiler. This pull request removes this at compile time.

#### PR impact _(Make sure to add [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords))_
List of related issues/PRs this will solve:

 Impact                  | Issue/PR
------------------------ | ------
Issues this solves       | Closes #191 
Other PRs this solves    | None

#### Proposed fix _(Make sure you've read [on how to contribute](https://github.com/TheCherno/Hazel/blob/master/.github/CONTRIBUTING.md) to Hazel)_
I added a new function (Clean_Expression) and a struct (Fixed_String) to the Instrumentor.h file and changed the HZ_PROFILE_FUNCTION macro to use it.
The Clean_Expression function goes through the output and removes the "__cdecl" from it.

#### Additional context
So nice as this works we still have the problem, that MSVC replaces things like "std::string" with "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >" or "glm::vec3" with something like "glm::vec<3,float,0>" .. and that doesn't really look nice.

EDIT by @LovelySanta: linked the related issue

### CODE REVIEW

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 1]
```diff
@@ -9,6 +9,36 @@
...
+	struct Fixed_String {
+		char data[N];
+	};
+
+	template <size_t N>
+	constexpr auto Clean_Expression(const char(&expr)[N]) {
+		Fixed_String<N> result = {};
+
+		int src_idx = 0;
+		int dst_idx = 0;
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:22]: string size is a size_t and again some coding convention (not use `_`)
```suggestion
		size_t srcIndex = 0;
		size_t dstIndex = 0;
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 2]
```diff
@@ -157,7 +187,7 @@ namespace Hazel {
 	};
 }
 
-#define HZ_PROFILE 0
+#define HZ_PROFILE 1
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:190]: Do not enable profiling in a PR, only for testing
```suggestion
#define HZ_PROFILE 0
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 3]
```diff
@@ -166,7 +196,7 @@ namespace Hazel {
 		#define HZ_FUNC_SIG __PRETTY_FUNCTION__
 	#elif defined(__DMC__) && (__DMC__ >= 0x810)
 		#define HZ_FUNC_SIG __PRETTY_FUNCTION__
-	#elif defined(__FUNCSIG__)
+	#elif defined(_MSC_VER)
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:199]: I thought MVS defined `__FUNCSIG__` at the start of the precompiler? If not, I think we should at least leave it?
```suggestion
	#elif defined(__FUNCSIG__ || _MSC_VER)
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 4]
```diff
@@ -183,7 +213,7 @@ namespace Hazel {
 	#define HZ_PROFILE_BEGIN_SESSION(name, filepath) ::Hazel::Instrumentor::Get().BeginSession(name, filepath)
 	#define HZ_PROFILE_END_SESSION() ::Hazel::Instrumentor::Get().EndSession()
 	#define HZ_PROFILE_SCOPE(name) ::Hazel::InstrumentationTimer timer##__LINE__(name);
-	#define HZ_PROFILE_FUNCTION() HZ_PROFILE_SCOPE(HZ_FUNC_SIG)
+	#define HZ_PROFILE_FUNCTION() HZ_PROFILE_SCOPE(::Hazel::Clean_Expression(HZ_FUNC_SIG).data)
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:216]: I am still debating with myself, should the cleanup be the part outside the macro, or should the cleanup be part of the `HZ_FUNC_SIG` itself?
```cpp
#define HZ_FUNC_SIG __FUNCSIG__
#define HZ_PROFILE_FUNCTION() HZ_PROFILE_SCOPE(::Hazel::Clean_Expression(HZ_FUNC_SIG).data)
```
versus
```cpp
#define HZ_FUNC_SIG ::Hazel::Clean_Expression(__FUNCSIG__).data
#define HZ_PROFILE_FUNCTION() HZ_PROFILE_SCOPE(HZ_FUNC_SIG)
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 5]
```diff
@@ -9,6 +9,36 @@
 
 namespace Hazel {
 
+	template <size_t N>
+	struct Fixed_String {
```
[the remark this answers is not in the document]
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 6]
```diff
@@ -9,6 +9,36 @@
...
+		char data[N];
+	};
+
+	template <size_t N>
+	constexpr auto Clean_Expression(const char(&expr)[N]) {
```
[the remark this answers is not in the document]
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 5 above)
[the remark this answers is not in the document]
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 1 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 2 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 3 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 4 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: I think the place where it is right now is the perfect spot

Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: HZ_FUNC_SIG changes depending on the used compiler - so we should wrap the CleanExpression function around that.

Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done.

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 7]
```diff
@@ -9,6 +9,38 @@
 
 namespace Hazel {
 
+	template <size_t N>
+	struct CleanExpressionResult
+	{
+		char Data[N];
+	};
```
Comment (8infy) [inline Hazel/src/Hazel/Debug/Instrumentor.h:16]: Wouldn't `std::array` work for this as well?

Comment (LovelySanta) [reply Hazel/src/Hazel/Debug/Instrumentor.h:16]: It would, but a raw char array will work just fine

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 8]
```diff
@@ -9,6 +9,38 @@
 
 namespace Hazel {
 
+	template <size_t N>
+	struct CleanExpressionResult
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:13]: Rename to `ExpressionResult` or `FunctionSignatureResult`?

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 9]
```diff
@@ -9,6 +9,38 @@
...
+	{
+		char Data[N];
+	};
+
+	template <size_t N>
+	constexpr auto CleanExpression(const char(&expr)[N])
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:19]: Rename to `RemoveCdecl`

```suggestion
	constexpr auto RemoveCdecl(const char(&expr)[N])
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 10]
```diff
@@ -9,6 +9,38 @@
...
+				expr[srcIndex + 7] == ' ')
+			{
+				srcIndex += 8;
+			}
+			result.Data[dstIndex++] = expr[srcIndex++];
+		}
+		result.Data[dstIndex++] = expr[N - 2];
+		result.Data[dstIndex++] = expr[N - 1];
+		return result;
+	}
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:42]: Put inside namespace `::Hazel::InstrumentorUtils`

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 9 above)
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:19]: Make an equivalent function `ReplaceQuotes` for inside the `HZ_PROFILE_SCOPE` macro, so we can remove these lines
https://github.com/TheCherno/Hazel/blob/47126d585ae56ceebb3fdeae1da635d1c240b02e/Hazel/src/Hazel/Debug/Instrumentor.h#L113-L114

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 8 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Changed it to ChangeResult.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 9 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 10 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 9 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: Done.

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 11]
```diff
@@ -9,6 +9,64 @@
...
+		};
+
+		template <size_t N>
+		constexpr auto RemoveCdecl(const char(&expr)[N])
+		{
+			ChangeResult<N> result = {};
+
+			size_t srcIndex = 0;
+			size_t dstIndex = 0;
+			while (srcIndex < N - 2) {
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:27]:
```suggestion
			while (srcIndex < N - 2)
			{
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 12]
```diff
@@ -9,6 +9,64 @@
...
+		template <size_t N>
+		struct ChangeResult
+		{
+			char Data[N];
+		};
+
+		template <size_t N>
+		constexpr auto RemoveCdecl(const char(&expr)[N])
+		{
+			ChangeResult<N> result = {};
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:23]: Initializer list is not needed?

```suggestion
			ChangeResult<N> result;
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 13]
```diff
@@ -9,6 +9,64 @@
...
+		}
+
+		template <size_t N>
+		constexpr auto ReplaceQuotes(const char(&expr)[N])
+		{
+			ChangeResult<N> result = {};
+
+			size_t srcIndex = 0;
+			size_t dstIndex = 0;
+			while (srcIndex < N - 2) {
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:53]:
```suggestion
			while (srcIndex < N - 2)
			{
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 14]
```diff
@@ -9,6 +9,64 @@
...
+			}
+			result.Data[dstIndex++] = expr[N - 2];
+			result.Data[dstIndex++] = expr[N - 1];
+			return result;
+		}
+
+		template <size_t N>
+		constexpr auto ReplaceQuotes(const char(&expr)[N])
+		{
+			ChangeResult<N> result = {};
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:49]: Initializer list is not needed?

```suggestion
			ChangeResult<N> result;
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 15]
```diff
@@ -9,6 +9,64 @@
...
+			while (srcIndex < N - 2) {
+				if (expr[srcIndex] == '"')
+				{
+					result.Data[dstIndex++] = '\'';
+					srcIndex++;
+				}
+				else
+				{
+					result.Data[dstIndex++] = expr[srcIndex++];
+				}
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:62]: I think this might looks better for readability?
```suggestion
				result.Data[dstIndex++] = expr[srcIndex] == '"' ? '\'' : expr[srcIndex];
				srcIndex++;
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 16]
```diff
@@ -9,6 +9,64 @@
...
+				result.Data[dstIndex++] = expr[srcIndex++];
+			}
+			result.Data[dstIndex++] = expr[N - 2];
+			result.Data[dstIndex++] = expr[N - 1];
+			return result;
+		}
+
+		template <size_t N>
+		constexpr auto ReplaceQuotes(const char(&expr)[N])
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:47]: You forgot to actually delete the two lines that this function is replacing:
https://github.com/TheCherno/Hazel/blob/7bdbe9592e24a726583068da927bcebad08811c0/Hazel/src/Hazel/Debug/Instrumentor.h#L139-L140

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 17]
```diff
@@ -9,6 +9,64 @@
...
+		{
+			ChangeResult<N> result = {};
+
+			size_t srcIndex = 0;
+			size_t dstIndex = 0;
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:52]: This is optional, I think this is more preference from me, what do you think?
```suggestion
			size_t srcIndex = 0, dstIndex = 0;
```

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 18]
```diff
@@ -9,6 +9,64 @@
...
+			char Data[N];
+		};
+
+		template <size_t N>
+		constexpr auto RemoveCdecl(const char(&expr)[N])
+		{
+			ChangeResult<N> result = {};
+
+			size_t srcIndex = 0;
+			size_t dstIndex = 0;
```
Comment (LovelySanta) [inline Hazel/src/Hazel/Debug/Instrumentor.h:26]: This is optional, I think this is more preference from me, what do you think?
```suggestion
			size_t srcIndex = 0, dstIndex = 0;
```

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 11 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:27]: Changed.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 12 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:23]: Changed.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 13 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:53]: Changed.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 15 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:62]: Cleaner Code instead :) ... Changed.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 17 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:52]: I am not a fan of declaring multiple variables in the same line.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 18 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:26]: I am not a fan of declaring multiple variables in the same line.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 16 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:47]: Oh lol - yes :D
Fixed that.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 7 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h]: yes - raw char array will do the trick, too

**Comment by HerrDingenz** [comment]
In the last commit i moved the InstrumentorUtils namespace to the end of the file, right before the macros start. This looks more structured to me.

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 19]
```diff
@@ -155,6 +164,59 @@ namespace Hazel {
...
+			while (srcIndex < N - 2)
+			{
+				if (expr[srcIndex] == '_' &&
+					expr[srcIndex + 1] == '_' &&
+					expr[srcIndex + 2] == 'c' &&
+					expr[srcIndex + 3] == 'd' &&
+					expr[srcIndex + 4] == 'e' &&
+					expr[srcIndex + 5] == 'c' &&
+					expr[srcIndex + 6] == 'l' &&
+					expr[srcIndex + 7] == ' ')
```
Comment (8infy) [inline Hazel/src/Hazel/Debug/Instrumentor.h:192]: Can we align the indentation here?

File: Hazel/src/Hazel/Debug/Instrumentor.h [hunk 20]
```diff
@@ -137,7 +144,9 @@ namespace Hazel {
 		~InstrumentationTimer()
 		{
 			if (!m_Stopped)
+			{
 				Stop();
+			}
```
Comment (8infy) [inline Hazel/src/Hazel/Debug/Instrumentor.h:149]: Why did you add curly brackets here? They're redundant

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 19 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:192]: The intentation is only messed up here in github. Inside the file it is aligned as it should be.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 20 above)
Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:149]: To comply to the coding conventions.

Comment (HerrDingenz) [reply Hazel/src/Hazel/Debug/Instrumentor.h:149]: There are other places inside the code that has curly brackets on one-line if statements, too.
Look at lines 185 to 195 - that is a one-line statement, too .. should remove the curly brackets there, too?
Or look at lines 64 to 67 - there are curly brackets, too (in a one-line statement.

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 19 above)
Comment (8infy) [reply Hazel/src/Hazel/Debug/Instrumentor.h:192]: > The intentation is only messed up here in github. Inside the file it is aligned as it should be.

Ah yes, I forgot that we're using actual tabs here

File: Hazel/src/Hazel/Debug/Instrumentor.h (hunk 20 above)
Comment (8infy) [reply Hazel/src/Hazel/Debug/Instrumentor.h:149]: As long as that's the code style that this project follows, I guess we should keep it consistent

**Comment by HerrDingenz** [comment]
Recoded the RemoveCdecl function. It is called CleanupOutputString now and takes in a string to remove as a second parameter and removes this string as often as it finds it.

And I added the profiler output files to .gitignore.

File: .gitignore [hunk 21]
```diff
@@ -5,6 +5,9 @@ bin-int/
 
 # Hazel files
 *.log
+HazelProfile-Startup.json
+HazelProfile-Runtime.json
+HazelProfile-Shutdown.json
```
Comment (LovelySanta) [inline .gitignore:10]: Do not add these to `.gitignore`. Cherno does not want them in the code, later he only wants a single folder with all the rubbish here. Hence why the code on github is pushed without these files and with the profiler off, such that PRs do not carry profile results.

Comment (HerrDingenz) [reply .gitignore]: But the problem is: everytime i want to push new code and i ran it with profiling turned on i have to delete those files manually to prevent them from being pushed. and that sucks.
