### PR TITLE
ImGuizmo Crash Fix

### LINKED ISSUE #383: Crash when changing gizmos while using them
#### Description
Found an issue, if you change gizmos while using it, it will crash

#### My fix
i fixed it by locking the changing when i use it. not the best but it works
Im opening this issue, because i know that my fix is not the best and can be improved

#### Reproduce
To Reproduce: Try moving an object and change the gizmos to rotation / scale while you're moving it

### PR DESCRIPTION
**Pull request by twarug**
The issue

When you change a gizmo while using it, it will crash entire engine.

List of related issues/PRs this will solve:
- Crash when changing gizmos while using them #383

 Impact                  | Issue/PR
------------------------ | ------
Issues this solves       | Resolves #383
Other PRs this solves    | None

Proposed fix:

Disable and Enabel ImGuizmos after gizmo change.

### CODE REVIEW

**Comment by LovelySanta** [comment]
I find this more of a 'workaround' than an actual fix... When you're 'using' (read as fine tuning) an ImGuizmo I assume that pressing the switch buttons is rather an accident compared to the oposite (switching intended and 'using' an accident).

For this reason I would prefer to implement it as follows, when pressing the keys, check for `ImGuizmo::IsUsing()` and only switch modes when it is not being used?

I feel like that's a cleaner solution rather than what is proposed here? Feel free to prove me wrong?

**Comment by twarug** [comment]
I think that your solution is better. I decide to solve it in that way, becouse that is behaviour in Unity, wich i use a lot. I can iplement your solution? or cloase a pull request.

**Comment by FahimFuad** [comment]
@twarug You can just make another commit, and the changes will be applied automatically 🙂

File: Hazelnut/src/EditorLayer.cpp [hunk 1]
```diff
@@ -303,7 +303,7 @@ namespace Hazel {
 		if (e.GetRepeatCount() > 0)
 			return false;
 
-		int gizmoChange = -2;
+		bool canGizmoChange = !ImGuizmo::IsUsing();
```
Comment (LovelySanta) [inline Hazelnut/src/EditorLayer.cpp:306]: no need to store it as a variable, it is only used in the switch case anyway (once)

```suggestion

```

Comment (twarug) [reply Hazelnut/src/EditorLayer.cpp:306]: yes, but in the future can, be more conditions to change gizmo

Comment (LovelySanta) [reply Hazelnut/src/EditorLayer.cpp:306]: We can change it in the future then.. now it's just bloating the code...
