### PR TITLE
Fix wrong viewport bounds when tab is visible

### LINKED ISSUE #401: Incorrect viewport position being fed to ImGuizmo
#### Describe the bug
ImGuizmo::SetRect(...) is being fed with ImGui::GetWIndowPos() which does not account for tab bar height, this causes ImGuizmo to render widgets in the wrong position when the tab bar is visible.

#### To Reproduce
1. Clone master branch
2. Build project
3. Run Hazelnut
4. Open the tab bar in the Viewport pane

#### Expected behavior
The expected behavior is that the ImGuizmo widget would remain stationary in regards to the 3d geometry (The delta between widget origin in screen space and the object origin in screen space should not change.

#### Screenshots

Using ImGui::GetWindowPos() (Hazel master Pink line is actual position, Blue is desired position)
hz_viewport_position

Using ImGui::GetCursorScreenPos() (forked repository branch, Blue is actual position)
hz_viewport_position_fix

#### Operating system: (please complete the following information)
- OS: Windows 64 Bit
- Version: Pro

#### Additional context
Did some searching and found a reply from ocornut (ImGui Developer) suggesting use of GetCursorScreenPos
https://discourse.dearimgui.org/t/how-to-know-if-a-tab-bar-of-a-docked-window-is-hidden-and-its-height/316/5

### PR DESCRIPTION
**Pull request by lfilipozzi**
#### Describe the issue (if no issue has been made)
The viewport bound does not account for the tab bar correctly. As a result, when the tab bar is visible, the mouse picking is vertically offset. Also, when the cursor is right below the tab bar, `Framebuffer::ReadPixel()` returns an undefined integer.

ezgif com-gif-maker

#### PR impact _(Make sure to add [closing keywords](https://help.github.com/en/articles/closing-issues-using-keywords))_
List of related issues/PRs this will solve:

 Impact                  | Issue/PR
------------------------ | ------
Issues this solves       | Resolves #401
Other PRs this solves    | Closes #402

#### Proposed fix 
Redefine m_ViewportBounds in EditorLayer.cpp by using `ImGui::GetWindowContentRegionMin()` and `ImGui::GetWindowContentRegionMax()` instead of `ImGui::GetCursorPos()`.

#### Additional context
The fix works with a visible and a hidden viewport tab bar.

Using `ImGui::GetForegroundDrawList()->AddRect(minBound, maxBound, IM_COL32(255, 255, 0, 255));` in EditorLayer.cpp to highlight the viewport edges also shows the viewport vertical bounds is not correct when the tab bar is present.

Before fix (note the bottom edge):
bug

After fix:
fix

___
Edit by @LovelySanta: Added PR impact and moved parts of description to additional context

### CODE REVIEW

File: Hazelnut/src/EditorLayer.cpp [hunk 1]
```diff
@@ -236,7 +236,16 @@ namespace Hazel {
...
+		ImVec2 minBound = ImGui::GetWindowContentRegionMin();
+		ImVec2 maxBound = ImGui::GetWindowContentRegionMax();
+
+		minBound.x += ImGui::GetWindowPos().x;
+		minBound.y += ImGui::GetWindowPos().y;
+		maxBound.x += ImGui::GetWindowPos().x;
+		maxBound.y += ImGui::GetWindowPos().y;
+
+		m_ViewportBounds[0] = { minBound.x, minBound.y };
+		m_ViewportBounds[1] = { maxBound.x, maxBound.y };
```
Comment (LovelySanta) [inline Hazelnut/src/EditorLayer.cpp:248]:
```suggestion
		auto viewportMinRegion = ImGui::GetWindowContentRegionMin();
		auto viewportMaxRegion = ImGui::GetWindowContentRegionMax();
		auto viewportOffset = ImGui::GetWindowPos();
		m_ViewportBounds[0] = { viewportMinRegion.x + viewportOffset.x, viewportMinRegion.y + viewportOffset.y };
		m_ViewportBounds[1] = { viewportMaxRegion.x + viewportOffset.x, viewportMaxRegion.y + viewportOffset.y };
```

File: Hazelnut/src/EditorLayer.cpp [hunk 2]
```diff
@@ -248,25 +257,14 @@ namespace Hazel {
...
 		Entity selectedEntity = m_SceneHierarchyPanel.GetSelectedEntity();
 		if (selectedEntity && m_GizmoType != -1)
 		{
 			ImGuizmo::SetOrthographic(false);
 			ImGuizmo::SetDrawlist();
 
-			float windowWidth = (float)ImGui::GetWindowWidth();
-			float windowHeight = (float)ImGui::GetWindowHeight();
-			ImGuizmo::SetRect(ImGui::GetWindowPos().x, ImGui::GetWindowPos().y, windowWidth, windowHeight);
+			ImGuizmo::SetRect(minBound.x, minBound.y, maxBound.x - minBound.x, maxBound.y - minBound.y);
```
Comment (LovelySanta) [inline Hazelnut/src/EditorLayer.cpp:267]:
```suggestion
			ImGuizmo::SetRect(m_ViewportBounds[0].x, m_ViewportBounds[0].y, m_ViewportBounds[1].x - m_ViewportBounds[0].x, m_ViewportBounds[1].y - m_ViewportBounds[0].y);
```

**Review by LovelySanta — APPROVED** [review]
Cherno prefers to use `auto` over the ImGui types (`ImVec2`)... Other than that, I suggested some readability changes (but thats more personal tho)
